[package]
name = "stowsave"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
thiserror = "1"
pathdiff = "0.2"
path-clean = "1"
clap = { version = "4", features = ["derive"] }
fs_extra = "1"
[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
