name: RustBuildTest
on:
  "push": {"branches": ["main"]}
  "pull_request": {"branches": ["main"]}
env: {"CARGO_TERM_COLOR": "always"}
jobs:
  build_and_test:
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --verbose
      - run: cargo test --verbose
    runs-on: ${{ matrix.os }}
    "strategy": {"matrix": {"os": [ubuntu-latest, macos-latest]}}
